export enum PlatformRole {
  SELLER_USER = "SELLER_USER",
  BUYER_USER = "BUYER_USER",
  EXPERT_USER = "EXPERT_USER",
  INTERNAL_DEAL_MANAGER = "INTERNAL_DEAL_MANAGER",
  ADMIN = "ADMIN",
}

export enum DealRole {
  SELLER_OWNER = "SELLER_OWNER",
  SELLER_OPERATOR = "SELLER_OPERATOR",
  BUYER_OWNER = "BUYER_OWNER",
  BUYER_OPERATOR = "BUYER_OPERATOR",
  SELLER_ADVISOR = "SELLER_ADVISOR",
  BUYER_ADVISOR = "BUYER_ADVISOR",
  EXPERT = "EXPERT",
  INTERNAL_MANAGER = "INTERNAL_MANAGER",
}

export enum InformationState {
  CONFIRMED = "CONFIRMED",
  ESTIMATED = "ESTIMATED",
  UNKNOWN = "UNKNOWN",
}

export enum ApprovalStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  REVOKED = "REVOKED",
}

export enum ExpertAssignmentStatus {
  INVITED = "INVITED",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  REVOKED = "REVOKED",
}

export enum DDWorkstream {
  FDD = "FDD",
  LDD = "LDD",
  TAX_DD = "TAX_DD",
  CDD = "CDD",
  TDD = "TDD",
  HR_DD = "HR_DD",
  ENVIRONMENTAL_DD = "ENVIRONMENTAL_DD",
}

export enum DealStage {
  DISCOVERY = "DISCOVERY",
  VALUATION = "VALUATION",
  BUYER_SEARCH = "BUYER_SEARCH",
  PREPARATION = "PREPARATION",
  TEASER = "TEASER",
  OUTREACH = "OUTREACH",
  NDA = "NDA",
  IM = "IM",
  MANAGEMENT_MEETING = "MANAGEMENT_MEETING",
  IOI = "IOI",
  LOI = "LOI",
  DD = "DD",
  FINAL_NEGOTIATION = "FINAL_NEGOTIATION",
  SPA = "SPA",
  CLOSING = "CLOSING",
}

export enum OpportunityStage {
  CANDIDATE = "CANDIDATE",
  APPROVED_FOR_CONTACT = "APPROVED_FOR_CONTACT",
  CONTACTED = "CONTACTED",
  INTERESTED = "INTERESTED",
  NDA_IN_PROGRESS = "NDA_IN_PROGRESS",
  NDA_COMPLETED = "NDA_COMPLETED",
  IM_RELEASED = "IM_RELEASED",
  MEETING = "MEETING",
  IOI = "IOI",
  LOI = "LOI",
  DD = "DD",
  FINAL_NEGOTIATION = "FINAL_NEGOTIATION",
  SPA = "SPA",
  CLOSED = "CLOSED",
  DROPPED = "DROPPED",
}

/** 사용자에게 보이는 상위 10단계. Deal Stage를 대체하지 않는다. */
export enum MacroMaProcessStage {
  TEASER_L1 = "TEASER_L1",
  NDA = "NDA",
  ADVISORY_L2 = "ADVISORY_L2",
  MANDATE = "MANDATE",
  CIM_IM = "CIM_IM",
  LOI = "LOI",
  DD = "DD",
  SPA = "SPA",
  CLOSING = "CLOSING",
  PMI = "PMI",
}

export enum MacroStageStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING_SELLER = "WAITING_SELLER",
  WAITING_BUYER = "WAITING_BUYER",
  WAITING_EXPERT = "WAITING_EXPERT",
  WAITING_DOCUMENT = "WAITING_DOCUMENT",
  WAITING_APPROVAL = "WAITING_APPROVAL",
  COMPLETED = "COMPLETED",
  BLOCKED = "BLOCKED",
}

export enum FindingSeverity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum ErrorCode {
  AUTH_REQUIRED = "AUTH_REQUIRED",
  COMPANY_VERIFICATION_REQUIRED = "COMPANY_VERIFICATION_REQUIRED",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  APPROVAL_REQUIRED = "APPROVAL_REQUIRED",
  INVALID_TRANSITION = "INVALID_TRANSITION",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  DATA_PROVIDER_UNAVAILABLE = "DATA_PROVIDER_UNAVAILABLE",
  ACTION_BLOCKED = "ACTION_BLOCKED",
  DOCUMENT_ACCESS_EXPIRED = "DOCUMENT_ACCESS_EXPIRED",
  EXPERT_SCOPE_VIOLATION = "EXPERT_SCOPE_VIOLATION",
  CONFLICT_CHECK_REQUIRED = "CONFLICT_CHECK_REQUIRED",
  ENV_NOT_CONFIGURED = "ENV_NOT_CONFIGURED",
  SUPABASE_UNAVAILABLE = "SUPABASE_UNAVAILABLE",
  DUPLICATE_EMAIL = "DUPLICATE_EMAIL",
  COMPANY_CREATE_FAILED = "COMPANY_CREATE_FAILED",
  MEMBERSHIP_CREATE_FAILED = "MEMBERSHIP_CREATE_FAILED",
}

export enum MembershipRole {
  OWNER = "OWNER",
  REPRESENTATIVE = "REPRESENTATIVE",
  EXECUTIVE = "EXECUTIVE",
  EMPLOYEE = "EMPLOYEE",
  COMPANY_ADMIN = "COMPANY_ADMIN",
}

export enum MembershipStatus {
  PENDING = "pending",
  ACTIVE = "active",
  REVOKED = "revoked",
}
